[manager]
prepend_keymap = [	
	{ on = ["g", "c"], run = "cd ~/.config", desc = "go to Config" },
	{ on = ["g", "D"], run = "cd ~/Downloads", desc = "go to Downloads" },
	{ on = ["g", "d", "h"], run = "cd ~/dev", desc = "go to Dev" },
	{ on = ["g", "d", "c"], run = "cd ~/dev/courses/", desc = "go to Cources" },
	{ on = ["g", "d", "s"], run = "cd ~/dev/sdks/", desc = "go to SDKS" },
	{ on = ["g", "d", "p"], run = "cd ~/dev/projects/", desc = "go to Projects" },

	{ on = "<C-n>", run = "create --dir", desc = "Create directory" },
	{ on = "<F2>", run = "rename --hovered", desc = "Create directory" },

	{ on = "<C-h>", run = "hidden toggle", desc = "Create directory" },
]
