[colors]

[colors.primary]
foreground = "#ffffff"  # Foreground color
background = "#1E1E1E"  # Background color

[colors.cursor]
text = "#1E1E1E"        # Cursor text color
cursor = "#ffffff"      # Cursor color

[colors.normal]
black   = "#241F31"     # Palette index 0
red     = "#C01C28"     # Palette index 1
green   = "#2EC27E"     # Palette index 2
yellow  = "#F5C211"     # Palette index 3
blue    = "#1E78E4"     # Palette index 4
magenta = "#9841BB"     # Palette index 5
cyan    = "#0AB9DC"     # Palette index 6
white   = "#C0BFBC"     # Palette index 7

[colors.bright]
black   = "#5E5C64"     # Palette index 8
red     = "#ED333B"     # Palette index 9
green   = "#57E389"     # Palette index 10
yellow  = "#F8E45C"     # Palette index 11
blue    = "#51A1FF"     # Palette index 12
magenta = "#C061CB"     # Palette index 13
cyan    = "#4FD2FD"     # Palette index 14
white   = "#F6F5F4"     # Palette index 15

